version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.googlecode.maven-download-plugin:download-maven-plugin
    versions:
    - 1.6.2
  - dependency-name: org.netbeans.api:org-openide-awt
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-openide-util
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.cluster:platform
    versions:
    - RELEASE122
  - dependency-name: org.netbeans.api:org-netbeans-api-htmlui
    versions:
    - RELEASE122
  - dependency-name: org.ow2.asm:asm
    versions:
    - "9.0"
  - dependency-name: org.apache.felix:maven-bundle-plugin
    versions:
    - 5.1.1
